"""added admins models

Revision ID: 8dc414427d3b
Revises: 5b3a92255c89
Create Date: 2026-01-08 23:52:54.819404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc414427d3b'
down_revision: Union[str, Sequence[str], None] = '5b3a92255c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'admins', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'name')
    # ### end Alembic commands ###
